dubbo:
  scan:
    base-packages: org.rpc.cloud.dubbo.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: spring-cloud://localhost:8500


server:
  port: 40000
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      discovery:
        enabled: false
        register-enabled: false
    zookeeper:
      enabled: false
    consul:
      discovery:
        enabled: true
        host: 127.0.0.1
        port: 8500
eureka:
  client:
    enabled: false

  main:
    allow-bean-definition-overriding: true
management:
  endpoints:
    web:
      exposure:
        include: '*'

